-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgfg+RGa/vKbnCJ/CK
ZItPSDfXYYkUgFfs3Xbv//BcMOygCgYIKoZIzj0DAQehRANCAASqRM3KP6kxRtDA
rnclCYkRrjdY8duWBjcNB5wspeAdjV0ym4DUNsGGvTwkvhuzPJcIX1V6q4TeMDZL
gT2gBgnF
-----END PRIVATE KEY-----